Repository hassio-addons/addon-home-panel, pull requests merged in 2021-01, with the labels that each got.

#72 Remove obsolete webui from configuration
  home-panel/config.json
Labels: maintenance

#73 Cleanup Supervisor service discovery
  home-panel/rootfs/etc/cont-init.d/discovery.sh
Labels: bugfix

#74 Update name
  home-panel/DOCS.md
Labels: documentation
