Repository hassio-addons/addon-home-panel, pull requests merged in 2021-02, with the labels that each got.

#75 Upgrade add-on base image to 9.1.2
  home-panel/Dockerfile
  home-panel/build.json
  home-panel/config.json
Labels: dependencies, major

#84 Upgrade add-on base image to 9.1.4
  home-panel/Dockerfile
  home-panel/build.json
Labels: dependencies

#88 Update path
  home-panel/rootfs/etc/cont-init.d/secrets.sh
  home-panel/rootfs/etc/services.d/home-panel/run
Labels: maintenance
