Repository hassio-addons/addon-home-panel, pull requests merged in 2021-11, with the labels that each got.

#154 ⬆️ Upgrades nodejs-current to 16.11.1-r0
  home-panel/Dockerfile
Labels: dependencies

#155 Switch to centralized GitHub Action Workflows
  .github/labels.yml
  .github/release-drafter.yml
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/labels.yaml
  .github/workflows/lock.yaml
  .github/workflows/pr-labels.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/stale.yaml
Labels: ci

#156 Migrate JSON config to YAML
  home-panel/build.json
  home-panel/build.yaml
  home-panel/config.json
  home-panel/config.yaml
Labels: refactor

#157 ⬆️ Upgrades add-on base image to 10.2.0
  home-panel/Dockerfile
  home-panel/build.yaml
Labels: dependencies

#159 ⬆ Upgrade add-on base image to 10.2.1
  home-panel/Dockerfile
  home-panel/build.yaml
Labels: dependencies

#160 Add yarn cache clean to cleanup stage of container build
  home-panel/Dockerfile
Labels: maintenance

#161 ⬆️ Upgrades add-on base image to 10.2.2
  home-panel/Dockerfile
  home-panel/build.yaml
Labels: dependencies
